### ISSUE TITLE
Subgraph request timeouts

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1184]
we should add an optional timeout for subgraph requests. Otherwise, in case of issues in the subgraph, in flight requests will accumulate in the router. Using a timeout puts a bound on that wait time, reduces resource usage and improves user experience (faster responses, even if partial)

**Comment by Nireeksha17** [comment]
ConnectError: [invalid_argument] timeout 75000ms must be <= 30000
    at errorFromJson (file:///home/runner/_work/_tool/node/22.13.0/x64/lib/node_modules/wgc/node_modules/@connectrpc/connect/dist/esm/protocol-connect/error-json.js:53:[19](https://github.com/EG-A-S/ng-shared-service/actions/runs/12742548810/job/35510852730#step:6:20))
    at errorFromJsonBytes (file:///home/runner/_work/_tool/node/22.13.0/x64/lib/node_modules/wgc/node_modules/@connectrpc/connect/dist/esm/protocol-connect/error-json.js:91:12)
    at next (file:///home/runner/_work/_tool/node/22.13.0/x64/lib/node_modules/wgc/node_modules/@connectrpc/connect/dist/esm/protocol-connect/transport.js:113:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.unary (file:///home/runner/_work/_tool/node/22.13.0/x64/lib/node_modules/wgc/node_modules/@connectrpc/connect/dist/esm/protocol-connect/transport.js:63:[20](https://github.com/EG-A-S/ng-shared-service/actions/runs/12742548810/job/35510852730#step:6:21))
    at async Object.publishFederatedSubgraph (file:///home/runner/_work/_tool/node/22.13.0/x64/lib/node_modules/wgc/node_modules/@connectrpc/connect/dist/esm/promise-client.js:73:26)
    at async Command.<anonymous> (file:///home/runner/_work/_tool/node/22.13.0/x64/lib/node_modules/wgc/dist/commands/subgraph/commands/publish.js:53:[22](https://github.com/EG-A-S/ng-shared-service/actions/runs/12742548810/job/35510852730#step:6:23))
    at async Command.parseAsync (/home/runner/_work/_tool/node/22.13.0/x64/lib/node_modules/wgc/node_modules/commander/lib/command.js:936:5)
    at async file:///home/runner/_work/_tool/node/22.13.0/x64/lib/node_modules/wgc/dist/index.js:8:5 {
  rawMessage: 'timeout 75000ms must be <= 30000',
  code: 3,
  metadata: Headers {
    'access-control-allow-credentials': 'true',
    'access-control-expose-headers': 'Grpc-Status, Grpc-Message, Grpc-Status-Details-Bin, Content-Encoding, Connect-Content-Encoding, Trailer-Response-Id',
    connection: 'keep-alive',
    'content-length': '72',
    'content-type': 'application/json',
    date: 'Mon, 13 Jan 20[25](https://github.com/EG-A-S/ng-shared-service/actions/runs/12742548810/job/35510852730#step:6:26) 07:31:42 GMT',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    vary: 'Origin'
  },
  details: [],


Facing this issues for Subgraph of cosmos

**Comment by nirbhaykumar1999** [comment]
I am also facing the same issue, any idea how to fix it @Nireeksha17

**Comment by Nireeksha17** [comment]
Hi @nirbhaykumar1999 ,

This issue arises from the latest release of the Cosmos wgc CLI, which introduced changes that are incompatible with the Cosmos Control Plane in your cluster maybe its running an older version of cosmo router. 

The Cosmos team has suggested updating the Control Plane to the newer version, which includes a fix for the above error. 

Fix : If your not playing for control plane upgrade you can downgrade the wgc CLI to a version that is compatible with the older Control Plane.
