### ISSUE TITLE
Using the SimpleSpanExporter instead of BatchSpanExporter

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2046]
we currently have issues with telemetry when the traffic increases, where some traces are missing, some traces are missing spans, and we can see logs like this:

```
2022-11-04T09:42:50.805799Z apollo-router/src/plugins/telemetry/mod.rs:1191 ERROR apollo_router::plugins::telemetry: OpenTelemetry trace error occurred: Exporter jaeger encountered the following error(s): thrift agent failed with message too long
2022-11-04T09:42:57.097444Z apollo-router/src/plugins/telemetry/mod.rs:1191 ERROR apollo_router::plugins::telemetry: OpenTelemetry trace error occurred: Exporter jaeger encountered the following error(s): thrift agent failed with message too long
2022-11-04T09:42:57.299729Z apollo-router/src/plugins/telemetry/mod.rs:1191 ERROR apollo_router::plugins::telemetry: OpenTelemetry trace error occurred: Exporter jaeger encountered the following error(s): thrift agent failed with message too long
```

For some context, the rust-opentelemetry crate separates the span processor, that records and aggregates spans, and the exporter, that is specific to the collector service (otlp, jaeger, datadog...). The [SimpleSpanProcessor documentation](https://docs.rs/opentelemetry/0.17.0/opentelemetry/sdk/trace/struct.SimpleSpanProcessor.html) indicates `Note that the simple processor exports synchronously every time a span is ended. If you find this limiting, consider the batch processor instead`. So, in fear of scalability issues, we went with the [BatchSpanProcessor](https://docs.rs/opentelemetry/latest/opentelemetry/sdk/trace/struct.BatchSpanProcessor.html). The `BatchSpanProcessor` works by starting a separate task that receives spans over a channel, so any other task that creates spans  sneds them directly and does not do anymore processing.

In theory the `BatchSpanProcessor` should give us better performance, but my hunch here was that with one central task handling spans created by a lot of concurrent requests, we are instead creating a bottleneck that will quickly get overloaded. And so by using the `SimpleSpanProcessor` instead, we could better handle the load, at the cost of CPU usage and more latency.

# Benchmarks

So I tested this idea by reproducing our CI benchmarks, with the "products" and "reviews" subgraphs, and the 5kB query, that generates 24 spans per query. I perform 100000 requests with 10 clients (it's not much because it's really easy to make the batch processor fall over, and sampling traces does not change anything). The router has 3 cores available.

## BatchSpanProcessor

(I removed the error log before compiling because it was taking too much time)

`hey` results:

```
Summary:                                                  
  Total:        77.0854 secs                              
  Slowest:      0.0351 secs                               
  Fastest:      0.0055 secs                               
  Average:      0.0077 secs                               
  Requests/sec: 1297.2631                                 
                                                          
                                                          
Response time histogram:                                  
  0.005 [1]     |                                         
  0.008 [92669] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 
  0.011 [7261]  |■■■                                      
  0.014 [11]    |                                         
  0.017 [9]     |                                         
  0.020 [15]    |                                         
  0.023 [9]     |                                         
  0.026 [5]     |                                         
  0.029 [3]     |                                         
  0.032 [4]     |                                         
  0.035 [13]    |                                         
                                                          
                                                          
Latency distribution:                                     
  10% in 0.0072 secs                                      
  25% in 0.0074 secs                                      
  50% in 0.0076 secs                                      
  75% in 0.0080 secs                                      
  90% in 0.0083 secs                                      
  95% in 0.0085 secs                                      
  99% in 0.0090 secs                                      
```

Jaeger only receives 2 traces, with 1 span each (the third one is from the initial test query I did separately before benchmarking)

![Screenshot from 2022-11-04 11-06-46](https://user-images.githubusercontent.com/119296/199956116-3dea334b-507d-45a4-bb4d-bc54e3bfb7fb.png)

The flamegraph shows that we spend 13% of CPU time in the span exporter (the column on the right)

![flamegraph-batchspan](https://user-images.githubusercontent.com/119296/199956268-37846fdb-badb-4af0-b580-be883baa3e98.svg)

Overall the router uses 55% of each core to handle that load

## SimpleSpanProcessor, sampling at 100%

it is slower and latency is less table than the `BatchSpanProcessor`
```
Summary:                                                 
  Total:        90.8695 secs                             
  Slowest:      0.0776 secs                              
  Fastest:      0.0055 secs                              
  Average:      0.0091 secs                              
  Requests/sec: 1100.4789                                
                                                         
                                                         
Response time histogram:                                 
  0.005 [1]     |                                        
  0.013 [96428] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.020 [1408]  |■                                       
  0.027 [1229]  |■                                       
  0.034 [564]   |                                        
  0.042 [242]   |                                        
  0.049 [89]    |                                        
  0.056 [20]    |                                        
  0.063 [9]     |                                        
  0.070 [8]     |                                        
  0.078 [2]     |                                        
                                                         
                                                         
Latency distribution:                                    
  10% in 0.0078 secs                                     
  25% in 0.0081 secs                                     
  50% in 0.0085 secs                                     
  75% in 0.0090 secs                                     
  90% in 0.0096 secs                                     
  95% in 0.0103 secs                                     
  99% in 0.0265 secs                                     
```

But jaeger receives all the traces:

![Screenshot from 2022-11-04 11-21-13](https://user-images.githubusercontent.com/119296/199956751-4ca8f09a-d17a-4518-981b-96a97e034529.png)

We see in the flamegraph that we now spend 20% of CPU time in the `SimpleSpanProcessor`. The router uses 85% of each core to handle that load.

![flamegraph-simplespan](https://user-images.githubusercontent.com/119296/199956837-a16ba91e-03b3-4a70-b105-c3796b3c22f2.svg)

So as expected, it is slower and uses more resources, but this is without any sampling.

## SimpleSpanProcessor, sampling at 1%

Same performance as `BatchSpanProcessor`:

```
Summary:                                                  
  Total:        78.1037 secs                              
  Slowest:      0.0260 secs                               
  Fastest:      0.0049 secs                               
  Average:      0.0078 secs                               
  Requests/sec: 1280.3484                                 
                                                          
                                                          
Response time histogram:                                  
  0.005 [1]     |                                         
  0.007 [2550]  |■                                        
  0.009 [96278] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 
  0.011 [1099]  |                                         
  0.013 [44]    |                                         
  0.015 [18]    |                                         
  0.018 [1]     |                                         
  0.020 [4]     |                                         
  0.022 [4]     |                                         
  0.024 [0]     |                                         
  0.026 [1]     |                                         
                                                          
                                                          
Latency distribution:                                     
  10% in 0.0072 secs                                      
  25% in 0.0074 secs                                      
  50% in 0.0077 secs                                      
  75% in 0.0081 secs                                      
  90% in 0.0085 secs                                      
  95% in 0.0087 secs                                      
  99% in 0.0092 secs
```

As expected, Jaeger receives less traces, but they are still complete:

![Screenshot from 2022-11-04 11-31-53](https://user-images.githubusercontent.com/119296/199957770-dbd75e17-2ac0-4215-8c2a-b019c3c08e83.png)

It is now barely noticeable in the flamegraph (0.5% of CPU time, the column on the left), the router uses 50% of each core

![flamegraph](https://user-images.githubusercontent.com/119296/199958004-d710b1ac-1ba6-4696-b363-ee5cb2ba1b5a.svg)

## Conclusion

If we use the `BatchSpanProcessor`, as soon as there's some traffic it breaks and we don't receives traces. With `SimpleSpanProcessor` and trace sampling, we receive full traces and it's as fast as the batch processor

**Comment by Geal** [comment]
Correcting a confusion:

the `SimpleSpanProcessor` uses a separate thread and sends the spans over a channel:

https://github.com/open-telemetry/opentelemetry-rust/blob/v0.17.0/opentelemetry/src/sdk/trace/span_processor.rs#L112-L171

```rust
impl SimpleSpanProcessor {
    pub(crate) fn new(mut exporter: Box<dyn SpanExporter>) -> Self {
        let (span_tx, span_rx) = crossbeam_channel::unbounded();
        let (shutdown_tx, shutdown_rx) = crossbeam_channel::bounded(0);

        let _ = thread::Builder::new()
            .name("opentelemetry-exporter".to_string())
            .spawn(move || {
                while let Ok(Some(span)) = span_rx.recv() {
                    if let Err(err) = futures_executor::block_on(exporter.export(vec![span])) {
                        global::handle_error(err);
                    }
                }

                exporter.shutdown();

                if let Err(err) = shutdown_tx.send(()) {
                    global::handle_error(TraceError::from(format!(
                        "could not send shutdown: {:?}",
                        err
                    )));
                }
            });

        SimpleSpanProcessor {
            sender: span_tx,
            shutdown: shutdown_rx,
        }
    }
}

impl SpanProcessor for SimpleSpanProcessor {
    fn on_start(&self, _span: &mut Span, _cx: &Context) {
        // Ignored
    }

    fn on_end(&self, span: SpanData) {
        if let Err(err) = self.sender.send(Some(span)) {
            global::handle_error(TraceError::from(format!("error processing span {:?}", err)));
        }
    }

    fn force_flush(&self) -> TraceResult<()> {
        // Ignored since all spans in Simple Processor will be exported as they ended.
        Ok(())
    }

    fn shutdown(&mut self) -> TraceResult<()> {
        if self.sender.send(None).is_ok() {
            if let Err(err) = self.shutdown.recv() {
                global::handle_error(TraceError::from(format!(
                    "error shutting down span processor: {:?}",
                    err
                )))
            }
        }

        Ok(())
    }
}
```

The `BatchSpanProcessor` uses a task spawned on the runtime that aggregates the spans before sending to the exporter
https://github.com/open-telemetry/opentelemetry-rust/blob/v0.17.0/opentelemetry/src/sdk/trace/span_processor.rs#L243-L379

```rust
impl<R: TraceRuntime> SpanProcessor for BatchSpanProcessor<R> {
    fn on_start(&self, _span: &mut Span, _cx: &Context) {
        // Ignored
    }

    fn on_end(&self, span: SpanData) {
        let result = self.message_sender.try_send(BatchMessage::ExportSpan(span));

        if let Err(err) = result {
            global::handle_error(err);
        }
    }

    fn force_flush(&self) -> TraceResult<()> {
        let (res_sender, res_receiver) = oneshot::channel();
        self.message_sender
            .try_send(BatchMessage::Flush(Some(res_sender)))?;

        futures_executor::block_on(res_receiver)
            .map_err(|err| TraceError::Other(err.into()))
            .and_then(|identity| identity)
    }

    fn shutdown(&mut self) -> TraceResult<()> {
        let (res_sender, res_receiver) = oneshot::channel();
        self.message_sender
            .try_send(BatchMessage::Shutdown(res_sender))?;

        futures_executor::block_on(res_receiver)
            .map_err(|err| TraceError::Other(err.into()))
            .and_then(|identity| identity)
    }
}

/// Messages sent between application thread and batch span processor's work thread.
// In this enum the size difference is not a concern because:
// 1. If we wrap SpanData into a pointer, it will add overhead when processing.
// 2. Most of the messages will be ExportSpan.
#[allow(clippy::large_enum_variant)]
#[derive(Debug)]
pub enum BatchMessage {
    /// Export spans, usually called when span ends
    ExportSpan(SpanData),
    /// Flush the current buffer to the backend, it can be triggered by
    /// pre configured interval or a call to `force_push` function.
    Flush(Option<oneshot::Sender<ExportResult>>),
    /// Shut down the worker thread, push all spans in buffer to the backend.
    Shutdown(oneshot::Sender<ExportResult>),
}

impl<R: TraceRuntime> BatchSpanProcessor<R> {
    pub(crate) fn new(
        mut exporter: Box<dyn SpanExporter>,
        config: BatchConfig,
        runtime: R,
    ) -> Self {
        let (message_sender, message_receiver) =
            runtime.batch_message_channel(config.max_queue_size);
        let ticker = runtime
            .interval(config.scheduled_delay)
            .map(|_| BatchMessage::Flush(None));
        let timeout_runtime = runtime.clone();

        // Spawn worker process via user-defined spawn function.
        runtime.spawn(Box::pin(async move {
            let mut spans = Vec::new();
            let mut messages = Box::pin(stream::select(message_receiver, ticker));

            while let Some(message) = messages.next().await {
                match message {
                    // Span has finished, add to buffer of pending spans.
                    BatchMessage::ExportSpan(span) => {
                        spans.push(span);

                        if spans.len() == config.max_export_batch_size {
                            let result = export_with_timeout(
                                config.max_export_timeout,
                                exporter.as_mut(),
                                &timeout_runtime,
                                spans.split_off(0),
                            )
                            .await;

                            if let Err(err) = result {
                                global::handle_error(err);
                            }
                        }
                    }
                    // Span batch interval time reached or a force flush has been invoked, export current spans.
                    BatchMessage::Flush(res_channel) => {
                        let result = export_with_timeout(
                            config.max_export_timeout,
                            exporter.as_mut(),
                            &timeout_runtime,
                            spans.split_off(0),
                        )
                        .await;

                        if let Some(channel) = res_channel {
                            if let Err(result) = channel.send(result) {
                                global::handle_error(TraceError::from(format!(
                                    "failed to send flush result: {:?}",
                                    result
                                )));
                            }
                        } else if let Err(err) = result {
                            global::handle_error(err);
                        }
                    }
                    // Stream has terminated or processor is shutdown, return to finish execution.
                    BatchMessage::Shutdown(ch) => {
                        let result = export_with_timeout(
                            config.max_export_timeout,
                            exporter.as_mut(),
                            &timeout_runtime,
                            spans.split_off(0),
                        )
                        .await;

                        exporter.shutdown();

                        if let Err(result) = ch.send(result) {
                            global::handle_error(TraceError::from(format!(
                                "failed to send batch processor shutdown result: {:?}",
                                result
                            )));
                        }

                        break;
                    }
                }
            }
        }));

        // Return batch processor with link to worker
        BatchSpanProcessor { message_sender }
    }
```

so the inefficiency of the batch processor might be coming from something else than having a bottleneck task

**Comment by garypen** [comment]
This is an excellent investigation. One other thing to consider: maybe we need to configure our `BatchSpanProcessor` more carefully: https://docs.rs/opentelemetry/0.17.0/opentelemetry/sdk/trace/struct.BatchSpanProcessorBuilder.html

There are quite a few tuneables there that may be of interest, for example: [with_max_queue_size](https://docs.rs/opentelemetry/0.17.0/opentelemetry/sdk/trace/struct.BatchSpanProcessorBuilder.html#method.with_max_queue_size). It would also be interesting to look at the defaults for these values.

**Comment by Geal** [comment]
I tried tweaking these a while ago, and found that it is very hard to estimate them. The number of spans and the size of attributes and events varies wildly between queries. Jaeger uses thrift serialization and UDP packets, so it has a hard size limit, and it's  easy to go over it

**Comment by Geal** [comment]
sure! jaeger was only one data point, but the batch processor was used with all the other exporters. Now that #2047 can be tested, we can easily compare what happens with other exporters with or without batching. Note though that I spent a lot of time a year ago trying to find the right set of parameters for batching, and that was not successful. Maybe that can be revisited, but I'm not sure what else can be done on that part.

**Comment by Geal** [comment]
more tests:

## honeycomb (OTLP)

testing with a release router and honeycomb with the OTLP exporter, the logs fill up with:

```
2022-11-08T14:46:32.080746Z apollo-router/src/plugins/telemetry/mod.rs:1191 ERROR [trace_id=a422ec5ef5ded2c602d585ff32f74f6f] apollo_router::plugins::telemetry: OpenTelemetry trace error occurred: cannot send span to the batch span processor because the channel is full
```

Out of 1000 requests, it was able to send 2048 spans

With this PR, 4711 spans and counting (they take a while to get processed)

## zipkin

same as above, the router from the dev branch writes over and over in the logs:

```
2022-11-08T15:07:57.977144Z apollo-router/src/plugins/telemetry/mod.rs:1191 ERROR [trace_id=7064946cf88c039392eb255a3a71f091] apollo_router::plugins::telemetry: OpenTelemetry trace error occurred: cannot send span to the batch span processor because the channel is full
```

But apparently we got 1000 traces with 24 spans each as expected

With this PR, the router panics with:

```
2022-11-08T15:13:28.953209Z ERROR panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/geal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/context.rs:31:26
   0: apollo_router::executable::setup_panic_handler::{{closure}}                                
   1: std::panicking::rust_panic_with_hook                                                                             
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}} 
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13      
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   6: core::panicking::panic_display
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:72:5
   7: core::panicking::panic_str
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:56:5
   8: core::option::expect_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:1874:5
   9: tokio::runtime::context::io_handle
  10: tokio::io::poll_evented::PollEvented<E>::new
  11: tokio::net::tcp::stream::TcpStream::new
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  20: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  21: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  22: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
  23: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
  24: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  26: <hyper::client::client::ResponseFuture as core::future::future::Future>::poll
  27: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
  28: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  31: std::thread::local::LocalKey<T>::with
  32: futures_executor::local_pool::block_on
  33: std::sys_common::backtrace::__rust_begin_short_backtrace
```

**Comment by Geal** [comment]
OTLP with the BatchSpanProcessor  does not have the log for the full channel when sampling at 1%

**Comment by BrynCooke** [comment]
Closing as after experimentation it seems that BatchSpanProcessor gives the user sufficient control to shape the trace traffic to an APM. Note that this is only on the otel_upgrade branch currently.
```
batch_processor:
        max_concurrent_exports: 1000 
        scheduled_delay: 100ms 
        max_queue_size: 100000 # Use this to smooth out peaks in your traffic 
        max_export_batch_size: 512 # Reduce this if your APM has a maximum message size and you are exceeding it.
        max_export_timeout: 10s
```
Peak export rate can be worked out using a combination of `max_concurrent_exports`, `scheduled_delay` and `max_export_batch_size`. The magic values for these will depend on APM and user traffic shape.

In future we may try and help users figure out what these values should be by using metrics, but in the short term we will update our documentation to help users understand these settings.
