### ISSUE TITLE
@defer: expected error not returned in specific case

### ISSUE THREAD

**Issue by BoD** [apollographql/router#2329]
With version 1.7.0.

This queries the field `nonNullErrorField` which throws an error:

```graphql
query HandlesNonNullableErrorsThrownInDeferredFragmentsQuery {
  computer(id: "Computer1") {
    __typename
    id
    ...ComputerNonNullableErrorField
  }
}

fragment ComputerNonNullableErrorField on Computer {
  nonNullErrorField
}
```

Result, as expected ✅:

```json
{
  "data": {
    "computer": null
  },
  "errors": [
    {
      "message": "Subgraph errors redacted",
      "locations": [
        {
          "line": 1,
          "column": 115
        }
      ],
      "path": [
        "computer",
        "nonNullErrorField"
      ]
    }
  ]
}
```

Now when deferring the fragment:

```graphql
query HandlesNonNullableErrorsThrownInDeferredFragmentsQuery {
  computer(id: "Computer1") {
    __typename
    id
    ...ComputerNonNullableErrorField @defer
  }
}
fragment ComputerNonNullableErrorField on Computer {
  nonNullErrorField
}
```

The error is no longer there in the response ❌:
```json
{
  "data": {
    "computer": null
  }
}
```

Received payloads are:
```
{"data":{"computer":null},"hasNext":true}
{"hasNext":false}
```

**Expected behavior**
```
{"data":{"computer":{"__typename":"computer","id":"Computer1"}},"hasNext":true}
{"hasNext":true,"incremental":[{"data":null,"errors":[{"message":"Subgraph errors redacted"}],"path":["computer"]}]}
{"hasNext":false}
```

**To reproduce**
```
git clone git@github.com:apollographql/apollo-kotlin.git
cd apollo-kotlin
(cd tests/defer/router/subgraphs/computers && npm install && APOLLO_PORT=4001 npm start)&
path/to/router --supergraph tests/defer/router/simple-supergraph.graphqls &
curl --request POST     --header 'content-type: application/json'     --header 'accept: multipart/mixed; deferSpec=20220824, application/json'     --url 'http://127.0.0.1:4000/'     --data '{"query":"query HandlesNonNullableErrorsThrownInDeferredFragmentsQuery {\n  computer(id: \"Computer1\") {\n    __typename\n    id\n    ...ComputerNonNullableErrorField @defer\n  }\n}\n\nfragment ComputerNonNullableErrorField on Computer {\n  nonNullErrorField\n}"}'
```

**Additional context**
I realize it is probably tricky to get 2 payloads, first with`id` and `__typename`, and 2nd with the error, due to the error bubbling up (as `nonNullErrorField` is non null). It would probably be ok to get only one payload? Not sure. But the missing error is probably a real issue at least.

**Comment by Geal** [comment]
what is received and sent back by the subgraph? I'm guessing only one request is sent? Is there a path on the error returned?

**Comment by BoD** [comment]
Yup, only one request, and there is a path.

Here's the query received by the subgraph:

```graphql
query HandlesNonNullableErrorsThrownInDeferredFragmentsQuery__computers__0{
  computer(id:"Computer1"){
    __typename id nonNullErrorField
  }
}
```

And here's its response:

```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Computer.nonNullErrorField.",
      "locations": [
        {
          "line": 2,
          "column": 42
        }
      ],
      "path": [
        "computer",
        "nonNullErrorField"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Computer.nonNullErrorField.",
            "    at completeValue (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/graphql/execution/execute.js:594:13)",
            "    at executeField (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/graphql/execution/execute.js:489:19)",
            "    at executeFields (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/graphql/execution/execute.js:413:20)",
            "    at completeObjectValue (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/graphql/execution/execute.js:914:10)",
            "    at completeValue (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/graphql/execution/execute.js:635:12)",
            "    at executeField (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/graphql/execution/execute.js:489:19)",
            "    at executeFields (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/graphql/execution/execute.js:413:20)",
            "    at executeOperation (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/graphql/execution/execute.js:344:14)",
            "    at execute (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/graphql/execution/execute.js:136:20)",
            "    at execute (/Users/bod/gitrepo/apollo-kotlin-0/tests/defer/router/subgraphs/computers/node_modules/apollo-server-core/dist/requestPipeline.js:205:48)"
          ]
        }
      }
    }
  ],
  "data": {
    "computer": null
  }
}
```

**Comment by BrynCooke** [comment]
@BoD There have been a lot of changes to defer since this was raised. Is this still an issue?

**Comment by BoD** [comment]
@BrynCooke Yes I can still repro this one with 1.32.0
