### ISSUE TITLE
regression: a recent change to the router broke router-bridge introspection

### ISSUE THREAD

**Issue by garypen** [apollographql/router#280]
**Describe the bug**
introspection fails when using the diagnose-endpoint client.

**To Reproduce**
When running the router, if you run
```
npx diagnose-endpoint@1.0.12 --endpoint=http://localhost:4000
```
you will see an error in the router:
```
thread 'tokio-runtime-worker' panicked at 'unable to invoke var _a;
Object.defineProperty(exports, "__esModule", { value: true });
const planResult = bridge.plan(schemaString, queryString, operationName);
if (((_a = planResult.errors) === null || _a === void 0 ? void 0 : _a.length) > 0) {
    done({ Err: planResult.errors });
}
else {
    done({ Ok: planResult.data });
}
//# sourceMappingURL=do_plan.js.map in JavaScript runtime 
 error: 
 Error: Error parsing args: missing field `node`
    at Object.opSync (deno:core/01_core.js:142:12)
    at done (<init>:7:15)
    at do_plan:8:5', /Users/garypen/.asdf/installs/rust/1.57.0/git/checkouts/federation-320f8bad94ab52a0/e88ce2a/router-bridge/src/js.rs:65:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'unable to invoke var _a;
Object.defineProperty(exports, "__esModule", { value: true });
const planResult = bridge.plan(schemaString, queryString, operationName);
if (((_a = planResult.errors) === null || _a === void 0 ? void 0 : _a.length) > 0) {
    done({ Err: planResult.errors });
}
else {
    done({ Ok: planResult.data });
}
//# sourceMappingURL=do_plan.js.map in JavaScript runtime 
 error: 
 Error: Error parsing args: missing field `node`
    at Object.opSync (deno:core/01_core.js:142:12)
    at done (<init>:7:15)
    at do_plan:8:5', /Users/garypen/.asdf/installs/rust/1.57.0/git/checkouts/federation-320f8bad94ab52a0/e88ce2a/router-bridge/src/js.rs:65:13
```
and the client will respond with:
```
⚠️  Introspection query received a response of {"hasNext":false,"errors":[{"message":"Query could not be planned: Cache resolution failed: Value retrieval failed: Query planning panicked: panic","locations":[],"path":null,"extensions":{"type":"ValidationPlanningError","reason":"Cache resolution failed: Value retrieval failed: Query planning panicked: panic"}}]}. Does introspection need to be turned on?
```
**Expected behavior**
No panic in the router and the client should work as expected.

**Output**
See above

**Desktop (please complete the following information):**
 - OS: OS X
 - Version Darwin Garys-MBP.mhs 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

**Additional context**
git bisect indicates that the likely cause of the issue is: https://github.com/apollographql/router/commit/c759f464e294fbdd8c08fa94257bba21ed016a66

**Comment by o0Ignition0o** [comment]
closed through #281
