### ISSUE TITLE
Panic due to unwrap()

### ISSUE THREAD

**Issue by andrew-kolesnikov** [apollographql/router#3951]
Receiving the following panic that I traced down to this line: https://github.com/apollographql/federation-rs/blob/6f72355b98d5389eba53625d0990d7cb0eb80ec9/federation-2/router-bridge/src/worker.rs#L98C19-L98C31

```
panicked at 'called `Result::unwrap()` on an `Err` value: TypeError: Error parsing args at position 1: missing field `id`
    at send (worker.js:51:25)
    at run (worker.js:164:19)
    at eventLoopTick (ext:core/01_core.js:181:11)', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/router-bridge-0.2.8+v2.4.8/src/worker.rs:98:38
Please consider handling the errors originating downstream without panics and provide more context.
```

**Comment by BrynCooke** [comment]
Hi @andrew-kolesnikov, Thanks for the report. 

Can you let us know which version of the Router you are using, if you have made any customizations, and when the panic occurs (router startup|serving a request).

If you can share your schema then that would be great. My email is bryn @ apollographql.com if you would prefer to share privately.

**Comment by abernix** [comment]
I'm going to close this since we haven't heard back from you, but happy to consider re-opening with additional information that helps us chase this down but please keep in mind that we don't [support using `router-bridge` directly](https://crates.io/crates/router-bridge).  😄
