### ISSUE TITLE
File uploads: Investigate failing integration test

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#4716]
One of the integration tests is [failing in CI](https://app.circleci.com/pipelines/github/apollographql/router/19278/workflows/2d63f5a8-207d-474d-bc07-d02e383474d6/jobs/128100).

Logs copied below:

```
---- integration::file_upload::it_fails_incompatible_query_order stdout ----
{"timestamp":"2024-02-22T14:51:54.011649109Z","level":"WARN","message":"RUST_BACKTRACE=full detected. This is useful for diagnostics but will have a performance impact and may leak sensitive information","target":"apollo_router::executable","resource":{}}
{"timestamp":"2024-02-22T14:51:54.015537241Z","level":"INFO","message":"Apollo Router v1.40.1 // (c) Apollo Graph, Inc. // Licensed as ELv2 (https://go.apollo.dev/elv2)","target":"apollo_router::executable","resource":{}}
{"timestamp":"2024-02-22T14:51:54.015592933Z","level":"INFO","message":"Anonymous usage data collection is disabled.","target":"apollo_router::executable","resource":{}}
{"timestamp":"2024-02-22T14:51:54.780286840Z","level":"INFO","message":"Apollo Studio usage reporting is enabled. See https://go.apollo.dev/o/data for details","target":"apollo_router::plugins::telemetry::metrics::apollo","spans":[{"name":"starting"},{"name":"plugins"},{"name":"plugin: apollo.telemetry"}],"resource":{}}
{"timestamp":"2024-02-22T14:51:54.813520463Z","level":"WARN","message":"telemetry.instrumentation.spans.mode is currently set to 'deprecated', either explicitly or via defaulting. Set telemetry.instrumentation.spans.mode explicitly in your router.yaml to 'spec_compliant' for log and span attributes that follow OpenTelemetry semantic conventions. This option will be defaulted to 'spec_compliant' in a future release and eventually removed altogether","target":"apollo_router::plugins::telemetry","spans":[{"name":"starting"},{"name":"plugins"},{"name":"plugin: apollo.telemetry"}],"resource":{}}
{"timestamp":"2024-02-22T14:51:54.853154435Z","level":"INFO","message":"Health check exposed at http://127.0.0.1:8088/health","target":"apollo_router::axum_factory::axum_http_server_factory","resource":{"process.executable.name":"router","service.name":"unknown_service:router","service.version":"1.40.1"}}
{"timestamp":"2024-02-22T14:51:54.862779432Z","level":"INFO","message":"GraphQL endpoint exposed at http://127.0.0.1:4000/ 🚀","target":"apollo_router::axum_factory::axum_http_server_factory","resource":{"process.executable.name":"router","service.name":"unknown_service:router","service.version":"1.40.1"}}
thread 'integration::file_upload::it_fails_incompatible_query_order' panicked at apollo-router/tests/integration/../common.rs:546:25:
unable to send successful request to router, error sending request for url (http://localhost:4000/): connection closed before message completed
stack backtrace:
   0:     0x55c9dcd895cc - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c9dcd895cc - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c9dcd895cc - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55c9dcd895cc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55c9dcdbc36c - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x55c9dcdbc36c - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x55c9dcd843ee - std::io::Write::write_fmt::h71a9c5feab76e44a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x55c9dcd893b4 - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55c9dcd893b4 - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55c9dcd8aff3 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x55c9dcd8ac97 - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:289:9
  11:     0x55c9d649b92c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h774b04429a49bf58
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
  12:     0x55c9d649b92c - test::test_main::{{closure}}::he7d0011bfc4f3b06
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/test/src/lib.rs:136:21
  13:     0x55c9dcd8b6f1 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h87b887549356728a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
  14:     0x55c9dcd8b6f1 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:735:13
  15:     0x55c9dcd8b471 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  16:     0x55c9dcd89af6 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  17:     0x55c9dcd8b1c2 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  18:     0x55c9d5ff9625 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  19:     0x55c9d6330dca - integration_tests::integration::common::IntegrationTest::execute_multipart_request::{{closure}}::{{closure}}::h1a17429190c5024e
                               at /home/circleci/project/apollo-router/tests/integration/../common.rs:546:25
  20:     0x55c9d63242a8 - <tracing_futures::Instrumented<T> as core::future::future::Future>::poll::h7d7a44e45f0f40d8
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-futures-0.2.5/src/lib.rs:283:9
  21:     0x55c9d63301be - integration_tests::integration::common::IntegrationTest::execute_multipart_request::{{closure}}::h96013d380ec66314
                               at /home/circleci/project/apollo-router/tests/integration/../common.rs:551:14
  22:     0x55c9d63249d7 - <tracing_futures::WithDispatch<T> as core::future::future::Future>::poll::{{closure}}::h3cd14d6535d898c4
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-futures-0.2.5/src/lib.rs:455:47
  23:     0x55c9d6306ae1 - tracing_core::dispatcher::with_default::ha4e1d6f8155cd1f5
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.31/src/dispatcher.rs:265:5
  24:     0x55c9d6324972 - <tracing_futures::WithDispatch<T> as core::future::future::Future>::poll::ha57a9812c9f08929
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-futures-0.2.5/src/lib.rs:455:9
  25:     0x55c9d60ae9a4 - integration_tests::integration::file_upload::helper::FileUploadTestServer::run_test::{{closure}}::h568bce7e6ee042b3
                               at /home/circleci/project/apollo-router/tests/integration/file_upload.rs:921:18
  26:     0x55c9d6356a6b - integration_tests::integration::file_upload::it_fails_incompatible_query_order::{{closure}}::h18068f5541be958a
                               at /home/circleci/project/apollo-router/tests/integration/file_upload.rs:786:10
  27:     0x55c9d609511d - <core::pin::Pin<P> as core::future::future::Future>::poll::h7649a9adfdc306fb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  28:     0x55c9d60eb9d3 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::hf92352e08e689ea3
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281:63
  29:     0x55c9d60eb2ce - tokio::runtime::coop::with_budget::hc002d9852d1068ce
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:107:5
  30:     0x55c9d60eb2ce - tokio::runtime::coop::budget::hffd7be1145fd9dfc
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:73:5
  31:     0x55c9d60eb2ce - tokio::runtime::park::CachedParkThread::block_on::hbb0a303c0daf51a1
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281:31
  32:     0x55c9d6369373 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h52f00c893bb87d93
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/blocking.rs:66:9
  33:     0x55c9d638dc62 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h91cb1ccc4a786783
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  34:     0x55c9d638d0b1 - tokio::runtime::context::runtime::enter_runtime::h7ccb3889b1983bce
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/runtime.rs:65:16
  35:     0x55c9d638db88 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h00937f6de822f25f
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  36:     0x55c9d61dc717 - tokio::runtime::runtime::Runtime::block_on::h646d95a8d7d12198
                               at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/runtime.rs:350:45
  37:     0x55c9d6353b5d - integration_tests::integration::file_upload::it_fails_incompatible_query_order::h65a9e527d3bff844
                               at /home/circleci/project/apollo-router/tests/integration/file_upload.rs:756:5
  38:     0x55c9d63539d7 - integration_tests::integration::file_upload::it_fails_incompatible_query_order::{{closure}}::hb56ebcd2d1a431df
                               at /home/circleci/project/apollo-router/tests/integration/file_upload.rs:718:49
  39:     0x55c9d6051676 - core::ops::function::FnOnce::call_once::h30500fbb30b50b22
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  40:     0x55c9d64a09bf - core::ops::function::FnOnce::call_once::heaa6bd10e636ddeb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  41:     0x55c9d64a09bf - test::__rust_begin_short_backtrace::h648a8e2968228ae1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/test/src/lib.rs:626:18
  42:     0x55c9d649fa4e - test::run_test_in_process::{{closure}}::h6f41f9e0cb0e01f3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/test/src/lib.rs:649:60
  43:     0x55c9d649fa4e - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdd10d814e6f87879
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panic/unwind_safe.rs:271:9
  44:     0x55c9d649fa4e - std::panicking::try::do_call::heb49837323e0a108
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  45:     0x55c9d649fa4e - std::panicking::try::h1c76451ee4678b45
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  46:     0x55c9d649fa4e - std::panic::catch_unwind::h4b3292a1ebe68a9f
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  47:     0x55c9d649fa4e - test::run_test_in_process::h199922650f75555c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/test/src/lib.rs:649:27
  48:     0x55c9d649fa4e - test::run_test::{{closure}}::hb30d8c3830867614
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/test/src/lib.rs:572:43
  49:     0x55c9d64689a3 - test::run_test::{{closure}}::hb1d502edb82ef10a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/test/src/lib.rs:600:41
  50:     0x55c9d64689a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::he3f111db4a527fe9
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:154:18
  51:     0x55c9d646dbdb - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h299d909fde7c9179
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/mod.rs:529:17
  52:     0x55c9d646dbdb - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he6b231f6e17e089a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panic/unwind_safe.rs:271:9
  53:     0x55c9d646dbdb - std::panicking::try::do_call::h8cb4761d7fda57dd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  54:     0x55c9d646dbdb - std::panicking::try::h6435307fbe31457d
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  55:     0x55c9d646dbdb - std::panic::catch_unwind::h4b6e302b6bf77b1a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  56:     0x55c9d646dbdb - std::thread::Builder::spawn_unchecked_::{{closure}}::h50f2e830ae0c6106
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/mod.rs:528:30
  57:     0x55c9d646dbdb - core::ops::function::FnOnce::call_once{{vtable.shim}}::hccc3c36abcb46f43
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  58:     0x55c9dcd90aa5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa37c25e0ad051b0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  59:     0x55c9dcd90aa5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9486bed8ab2e65ad
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  60:     0x55c9dcd90aa5 - std::sys::unix::thread::Thread::new::thread_start::hd28b46dbf5673d17
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/unix/thread.rs:108:17
  61:     0x7f426bdd4609 - start_thread
  62:     0x7f426bba2133 - clone
  63:                0x0 - <unknown>
```

**Comment by nicholascioli** [comment]
Can't reproduce. Trying in CI again.
